image: rust/latest
packages:
  - sqlite-dev
sources:
  - https://git.sr.ht/~taum/sanshain
tasks:
  - build: |
      cd SanshainService
      cargo build --release
  - test: |
      cd SanshainService
      cargo test
