image: alpine/latest
packages:
  - sqlite-dev
  - rust
  - cargo
  - openssl-dev
  - build-base
sources:
  - https://git.sr.ht/~taum/sanshain
tasks:
  - build: |
      cd sanshain
      cargo build --release
  - test: |
      cd sanshain
      cargo test
