apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sanshain.fullname" . }}-secrets
  labels:
    {{- include "sanshain.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  INITIAL_ADMIN_PASSWORD: {{ .Values.secrets.initialAdminPassword | b64enc | quote }}
