apiVersion: v1
kind: Secret
metadata:
  name: sanshain-secrets
  labels:
    app: sanshain
type: Opaque
data:
  # Base64 encoded values (echo -n "value" | base64)
  DATABASE_URL: ""
  INITIAL_ADMIN_PASSWORD: ""
