apiVersion: v1
kind: Secret
metadata:
  name: sanshain-secrets
  labels:
    app: sanshain
type: Opaque
data:
  # Base64 encoded DATABASE_URL
  # echo -n "postgres://user:pass@host/db" | base64
  DATABASE_URL: ""
